dev-migration:
	npx prisma migrate dev --preview-feature

run-migration:
	npx prisma migrate deploy --preview-feature

generate-schema:
	npm run generate

npm-setup:
	npm install;

init: run-migration generate-schema

build: npm-setup generate-schema
